/**
 * One-shot restore for the deep-diving TurnStatus modification.
 *
 * When pnpm updates dsh packages, the installed ui-conversation bundle is
 * overwritten with the pristine build and all captions/animations vanish.
 * Run this to detect that state and re-apply the whole patch chain:
 *
 *   node restore-all.mjs [--bundle=<path>]
 *
 * Steps: detect → (re)generate dicts if missing → apply → self-check → smoke.
 * Requires: ./dict-zh.txt, ./dict-en.txt, ./captions.json (generated by
 * generate-captions.mjs; if absent, they are regenerated first).
 */
import fs from "node:fs";
import { execSync } from "node:child_process";
import { resolveBundlePath } from "./paths.mjs";

const HERE = import.meta.dirname;
const BUNDLE = resolveBundlePath();
const run = (cmd) => execSync(cmd, { cwd: HERE, stdio: "inherit" });

const src = fs.readFileSync(BUNDLE, "utf8");
const hasPatch = src.includes("ddn-caption");
const countMatch = src.match(/const DDN_CAPTION_COUNT = (\d+);/);
const count = countMatch ? Number(countMatch[1]) : 0;

if (hasPatch && count === 120) {
  console.log(`bundle already patched (120 captions) in ${BUNDLE} — nothing to do.`);
  process.exit(0);
}
if (!fs.existsSync(`${HERE}/dict-zh.txt`)) {
  console.log("dict files missing — regenerating from the word pool…");
  run("node generate-captions.mjs 120");
}
console.log(hasPatch
  ? `bundle partially patched (count=${count}) in ${BUNDLE} — reapplying…`
  : `bundle is pristine (pnpm overwrote it) in ${BUNDLE} — reapplying the patch…`);
const bundleArg = `--bundle=${JSON.stringify(BUNDLE)}`;
run(`node apply-to-bundle.mjs ${bundleArg}`);
run(`node self-check.mjs ${bundleArg}`);
run(`node smoke-conversation.cjs ${bundleArg}`);
console.log("\nrestore complete — refresh the GUI page to see the effect.");
